version: '3'
services:
  container-student:
    volumes:
      - ./labs:/workspace/cryptol-course/labs
      - ./misc:/workspace/cryptol-course/misc
      - ./spec:/workspace/cryptol-course/spec
  container-author:
    volumes:
      - ./labs:/workspace/cryptol-course/labs
      - ./misc:/workspace/cryptol-course/misc
      - ./spec:/workspace/cryptol-course/spec
      - ./output:/workspace/cryptol-course/output
      - ./scripts:/workspace/cryptol-course/scripts
  container-dev:
    volumes:
      - .:/workspace/cryptol-course
